/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ln_himaxtouch_MainActivity */

#ifndef _Included_com_ln_himaxtouch_MainActivity
#define _Included_com_ln_himaxtouch_MainActivity
#define _Included_com_ln_himaxtouch_Phonestt
#define _Included_com_ln_himaxtouch_RegisterRWActivity
#define _Included_com_ln_himaxtouch_RawDataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ln_himaxtouch_MainActivity
 * Method:    writeCfg
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_MainActivity_writeCfg
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_ln_himaxtouch_MainActivity
 * Method:    readCfg
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_MainActivity_readCfg
        (JNIEnv *, jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_Phonestte_readCfg
        (JNIEnv *, jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_RegisterRWActivity_writeCfg
        (JNIEnv *, jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_RegisterRWActivity_readCfg
        (JNIEnv *, jobject, jobjectArray);
JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_Touchevent_writeCfg
        (JNIEnv *, jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_Touchevent_readCfg
        (JNIEnv *, jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_NodeDataSource_writeCfg
        (JNIEnv *, jobject, jobjectArray);

JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_NodeDataSource_readCfg
        (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
