/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ln_himaxtouch_MultiRegisterRWActivity */

#ifndef _Included_com_ln_himaxtouch_MultiRegisterRWActivity
#define _Included_com_ln_himaxtouch_MultiRegisterRWActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ln_himaxtouch_osc_hopping
 * Method:    writeCfg
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_MultiRegisterRWActivity_writeCfg
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_ln_himaxtouch_osc_hopping
 * Method:    readCfg
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_MultiRegisterRWActivity_readCfg
        (JNIEnv *, jobject, jobjectArray);
/*
 * Class:     com_ln_himaxtouch_osc_hopping
 * Method:    writeCfg
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_Show_1MultiRegisterRWActivity_writeCfg
        (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_ln_himaxtouch_osc_hopping
 * Method:    readCfg
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ln_himaxtouch_Show_1MultiRegisterRWActivity_readCfg
        (JNIEnv *, jobject, jobjectArray);
#ifdef __cplusplus
}
#endif
#endif
